require:
  - rubocop-md
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - .git/**/*
    - vendor/bundle/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/IndentationConsistency:
  Exclude:
    - README.md

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/LineLength:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - lib/fillable-pdf/itext.rb

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/MutableConstant:
  Enabled: false
